WARNING:tensorflow:AutoGraph could not transform <bound method NeuralNetwork.decode of <neural_network.NeuralNetwork object at 0x000001373D486770>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method NeuralNetwork.encode of <neural_network.NeuralNetwork object at 0x000001373D486770>> and will run it as-is.
Cause: mangled names are not yet supported
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Traceback (most recent call last):
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\main.py", line 25, in <module>
    for i, yi in enumerate(grid_x):
  File "C:\Users\motom\Desktop\Python\Sputnik_VAE\neural_network.py", line 169, in train
    self.generate_and_save_images(self, epoch, test_sample)
TypeError: NeuralNetwork.generate_and_save_images() takes 3 positional arguments but 4 were given
Epoch: 1, Test set ELBO: -108305.2421875, time elapse for current epoch: 294.09399342536926